<div class="container">
    <div class="row gallery-list d-flex justify-content-center">
        <div class="col-12 text-center pb-4 pb-sm-5">
            <a href="<?=$this->baseUrl;?>/galeria/" class="bttn bttn-sm m-0">Wróć do galerii</a>
        </div>
        <?php foreach($this->photos as $p) {?>
            <div class="col-6 col-md-4 col-lg-3">
                <div class="col-gallery-thumb">
                    <a href="<?=$this->filesUrl();?>/galeria/big/<?=$p->plik;?>" class="swipebox">
                        <img src="<?=$this->filesUrl();?>/galeria/thumbs/<?=$p->plik;?>" alt="Galeria">
                        <div></div>
                    </a>
                </div>
            </div>
        <?php } ?>
    </div>
</div>