<div class="title"><h1><?=$this->controlname;?> - <?=$this->inwestycja->nazwa;?></h1></div>
<div class="row-fluid">
	<div class="span12">
	<ul class="nav nav-tabs none">
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/"><span class="fa i-lista"></span>Lista inwestycji</a></li>
		<li class="active"><a href="<?=$this->baseUrl;?>/admin/inwestycje/pokaz/id/<?=$this->inwestycja->id;?>/"><span class="fa i-inwest"></span><?=$this->inwestycja->nazwa;?></a></li>
		<li><a href="<?=$this->baseUrl;?>/admin/inwestycje/dodaj-plan/id/<?=$this->inwestycja->id;?>/"><span class="fa i-image"></span>Plan</a></li>
	</ul>

		<div class="widget">
			<table width="100%" cellspacing="0" cellpadding="0" class="tableStatic adm" id="sortable">
				<thead>
					<tr>
					<th width="5%" style="text-align:center">ID</th>
					<th width="10%" style="text-align:center">Nazwa</th>
					<th width="10%" style="text-align:center">Metry</th>
					<th width="10%" style="text-align:center">Cena</th>
					<th width="10%" style="text-align:center">Cena<sup>2</sup></th>
					<th width="10%" style="text-align:center">Cena netto</th>
					<th width="10%" style="text-align:center">Pokoje</th>
					<th width="10%" style="text-align:center">Status</th>
					</tr>
				</thead>
				<tbody class="content">
				<?php foreach($this->rooms as $lista) { if($lista->type_id == 1){ ?>
				<tr>
					<td style="text-align:center"><?=$this->escape($lista->id);?></td>
					<td style="text-align:center"><?=$this->escape($lista->local_number);?></td>
					<td style="text-align:center"><?=$this->escape($lista->area);?></td>
					<td style="text-align:center"><?=$this->escape($lista->price);?></td>
					<td style="text-align:center"><?=$this->escape($lista->pricemkw);?></td>
					<td style="text-align:center"><?=$this->escape($lista->price_net);?></td>
					<td style="text-align:center"><?=$this->escape($lista->rooms);?></td>
					<td style="text-align:center"><?=statusCRM($lista->status_id);?></td>

				</tr>
				<?php } } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>