<footer>
    <div id="footer">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-9">
                    <div class="row">
                        <div class="col-6">
                            <p>Pruna Development sp z o.o.</p>
                            <p>ul. Piaskowa 9B, 09-100 Płońsk</p>
                        </div>
                        <div class="col-6 text-right">
                            <p><a href="">Polityka prywatności</a></p>
                            <p>Realizacja: <a href="">4DL</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<div id="cookies"><p><a href="" class="closecookies gradient">Zamknij</a><?= $this->header['cookies']; ?></p></div>

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">