<div class="header-holder">
    <header>
        <div id="nav" class="container-fluid p-0">
            <div class="row no-gutters">
                <div class="col-3">
                    <div id="logo">
                        <a href="<?=$this->baseUrl;?>/" class="d-block">
                            <img src="<?=$this->gfxUrl();?>/sadyba-logo.png" alt="<?= $this->header['nazwa']; ?>" width="220" height="70">
                        </a>
                    </div>
                </div>
                <div class="col-9">
                    <nav></nav>
                    <div class="mobilemenu"><a href="#" id="triggermenu">MENU</a></div>
                </div>
            </div>
        </div>
    </header>
</div>
<div id="megamenu-opacity"></div>