Dziękujemy za zainteresowanie Osiedlem Sadyba w Płońsku!

Poniżej znajdziesz szczegóły dotyczące tego wyjątkowego osiedla w Płońsku. W przedsprzedaży oferujemy mieszkania w budynkach nr 1-4 (etap I) oraz segmenty nr 1A, 1B, 2A i 2B (etap II).

Plan osiedla oraz karty lokali dostępnych w przedsprzedaży:<br>

https://www.sadybaplonsk.pl/files/upload/E1_M1.pdf Budynek 1 - mieszkanie na parterze: E1/M1
https://www.sadybaplonsk.pl/files/upload/E1_M2.pdf Budynek 1 - mieszkanie na piętrze: E1/M2
https://www.sadybaplonsk.pl/files/upload/E1_M3.pdf Budynek 2 - mieszkanie na parterze: E1/M3
https://www.sadybaplonsk.pl/files/upload/E1_M4.pdf Budynek 2 - mieszkanie na piętrze: E1/M4
https://www.sadybaplonsk.pl/files/upload/E1_M5.pdf Budynek 3 - mieszkanie na parterze: E1/M5
https://www.sadybaplonsk.pl/files/upload/E1_M6.pdf Budynek 3 - mieszkanie na piętrze: E1/M6
https://www.sadybaplonsk.pl/files/upload/E1_M7.pdf Budynek 4 - mieszkanie na parterze: E1/M7
https://www.sadybaplonsk.pl/files/upload/E1_M8.pdf Budynek 4 - mieszkanie na piętrze: E1/M8
https://www.sadybaplonsk.pl/files/upload/segment_1A.pdf Budynek 1 - Lokal A: E2/1A
https://www.sadybaplonsk.pl/files/upload/segment_1B.pdf Budynek 1 - Lokal B: E2/1B
https://www.sadybaplonsk.pl/files/upload/segment_2A.pdf Budynek 2 - Lokal A: E2/2A
https://www.sadybaplonsk.pl/files/upload/segment_2B.pdf Budynek 2 - Lokal B: E2/2B
https://www.sadybaplonsk.pl/files/upload/plan_osiedla_sadyba.pdf Plan osiedla

Wybierz swój nowy dom!
Tel. +48 696-651-133
e-mail: biuro@sadybaplonsk.pl

Administratorem danych osobowych jest PRUNA DEVELOPMENT sp. z o.o. siedzibą w Płońsku (09-100), ul. Piaskowa 9B, wpisana do rejestru przedsiębiorców w Krajowym Rejestrze Sądowym pod numerem KRS 0000874244, NIP: 5671922597, REGON: 38772003600000. Pełny tekst klauzuli informacyjnej i polityki prywatności dostępny jest na sadybaplonsk.pl