Dziękujemy za zainteresowanie Osiedlem Sadyba w Płońsku!

Wkrótce się z Tobą skontaktujemy.
Tel. +48 696-651-133
e-mail: biuro@sadybaplonsk.pl

Administratorem danych osobowych jest PRUNA DEVELOPMENT sp. z o.o. siedzibą w Płońsku (09-100), ul. Piaskowa 9B, wpisana do rejestru przedsiębiorców w Krajowym Rejestrze Sądowym pod numerem KRS 0000874244, NIP: 5671922597, REGON: 38772003600000. Pełny tekst klauzuli informacyjnej i polityki prywatności dostępny jest na sadybaplonsk.pl